<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Waiters\Dishes\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Waiters\Dishes\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Orders\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Orders\Delete.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Orders\Details.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Orders\Edit.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Orders\Index.cshtml" />
  </ItemGroup>

</Project>
